### ISSUE TITLE
FRONTEND : Add legends for colors of events 

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#103]
**SIZE : 3**

**Comment by gelaiong** [comment]
- Added legend (not sure sa description sa colors sa events)
![legend](https://user-images.githubusercontent.com/29205680/33953941-c56fa7d8-e071-11e7-8ebb-692324ba1438.JPG)

**Comment by jenadrianne** [comment]
commit id : 2a6af7e
