### ISSUE TITLE
FRONTEND : Users can only delete/cancel events that are still pending.

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#104]
**SIZE : 3**

**Comment by gelaiong** [comment]
- Pending events can be edited/deleted
![pending-edit](https://user-images.githubusercontent.com/29205680/33958090-7218cf9e-e07e-11e7-9511-9cc556bd5e64.JPG)

-Approved events cannot be deleted (from calendar)
![approved-edit](https://user-images.githubusercontent.com/29205680/33958123-8d155146-e07e-11e7-8968-16b132c9dd7a.JPG)

**Comment by jenadrianne** [comment]
commit id : 532979c
