### ISSUE TITLE
FRONTEND : Add confirmation modal before deleting an event

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#105]
**SIZE :2**

**Comment by gelaiong** [comment]
Added confirmation modal before deleting an event (from calendar)

![confirmdelete](https://user-images.githubusercontent.com/29205680/33958019-4457ab8e-e07e-11e7-83ee-d9015355cee4.JPG)

**Comment by jenadrianne** [comment]
commit id : 5f5cd2a
