### ISSUE TITLE
FRONTEND : CANNOT EDIT PAST EVENTS 

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#106]
**SIZE : 2** 

TASK DESCRIPTION :
Clicked past events will be redirected to event details page but the user cannot edit details anymore, instead of just showing error modal when clicking past events

**Comment by gelaiong** [comment]
-Cannot edit past events (from calendar)
![expired](https://user-images.githubusercontent.com/29205680/33958137-958efb24-e07e-11e7-9f72-b845652ba76b.JPG)

**Comment by gelaiong** [comment]
commit by: Dico
