### ISSUE TITLE
Dashboard: Events display is redirected to Page Not Found

### ISSUE THREAD

**Issue by wilburpatty** [ejmstark/event_system#190]
Should redirect to event's information page

**Comment by Dioven15** [comment]
SIZE: 3

**Comment by Dioven15** [comment]
d9c4383

**Comment by jenadrianne** [comment]
verified: 
![image](https://user-images.githubusercontent.com/23441105/34915055-b41d8b02-f959-11e7-8c27-5c165c4fa9f6.png)
