### ISSUE TITLE
Page Not Found: No link to return to page

### ISSUE THREAD

**Issue by wilburpatty** [ejmstark/event_system#191]
Sprint 4
Commit ID:

1f1e22e7f91c51551c1e1a88e1aad0be74477b3b

**Comment by gelaiong** [comment]
2 pts

**Comment by jenadrianne** [comment]
VERIFIED : 
![image](https://user-images.githubusercontent.com/23441105/34915007-ed1c60fa-f958-11e7-8f49-703ca7670fd8.png)
