### ISSUE TITLE
Create Event: Menu links inconsistent from dashboard

### ISSUE THREAD

**Issue by wilburpatty** [ejmstark/event_system#201]

**Comment by gelaiong** [comment]
3 pts

**Comment by gelaiong** [comment]
![create](https://user-images.githubusercontent.com/29205680/34726498-253ecdd8-f58f-11e7-9ea5-e2b4247baef3.JPG)

**Comment by gelaiong** [comment]
Commit id (Create event)
a426593

Commit id (Create event from Calendar)
cfa3519

**Comment by gelaiong** [comment]
Events Page Menu 
![image](https://user-images.githubusercontent.com/29205680/34729194-fbdce5da-f596-11e7-914f-8dbc8bb955f8.png)



Fixed

![image](https://user-images.githubusercontent.com/29205680/34729278-393ddd76-f597-11e7-94f3-85dc685c86de.png)

Commit id 
ad5373e

**Comment by jenadrianne** [comment]
@gelaiong  please verify in Live, it is still an issue

**Comment by gelaiong** [comment]
fixed
commit id: 
3589838
