### ISSUE TITLE
ADMIN: Create Announcement -> Text box goes outside of modal when dragged

### ISSUE THREAD

**Issue by Ted125** [ejmstark/event_system#416]
![screenshot 211](https://user-images.githubusercontent.com/20377215/36189383-2e987b9e-118d-11e8-9c87-28aeb5343d2a.png)

**Comment by leonillechristie** [comment]
commit id: ed417al

**Comment by leonillechristie** [comment]
commit id: 1d756382f71e5bef1cfa37da40e855ad6079dd20
SPRINT 7
3

**Comment by leonillechristie** [comment]
![image](https://user-images.githubusercontent.com/23441119/36305731-b437cf3e-134f-11e8-8a0c-b8c58b608340.png)
