### ISSUE TITLE
FRONTEND: User View -> Calendar -> I can add events when clicking the upper disable dates

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#56]
**STEPS :** 
- Click on the date that are grayed. 
![image](https://user-images.githubusercontent.com/23441105/33521963-c815b3e6-d81b-11e7-8f30-cdc5df69d62b.png)
- It redirects you to the create event page which should not happen 
![image](https://user-images.githubusercontent.com/23441105/33521975-11464bb6-d81c-11e7-8e3b-7d1419a75b7c.png)

**TASK** 
- [ ] disable the box fields and display the alert dialog 
![image](https://user-images.githubusercontent.com/23441105/33521984-4238280c-d81c-11e7-9f04-87b5528e0a03.png)

**Comment by gelaiong** [comment]
Na fix na ni

**Comment by jenadrianne** [comment]
![image](https://user-images.githubusercontent.com/23441105/33665823-1bc2cc86-dad3-11e7-8a61-1d706fd1321e.png)

692c0d7, 60a95d3
