### ISSUE TITLE
FRONTEND : User View -> Calendar -> Enhancements at View Event Page after clicking the event

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#58]
- click the event, 
![image](https://user-images.githubusercontent.com/23441105/33521999-bcf442f6-d81c-11e7-85e9-9dd5628c005a.png)

- supposed that it has redirected to the View Event page, instead of the edit page 
![image](https://user-images.githubusercontent.com/23441105/33522007-df4937d0-d81c-11e7-8dbf-6656740d6708.png)

- [x] add Button 'edit' and 'delete' 
![image](https://user-images.githubusercontent.com/23441105/33522044-b79a0696-d81d-11e7-90fd-459903d02c6b.png)

- [x] 'EDIT' button should redirect to edit event page 
![image](https://user-images.githubusercontent.com/23441105/33522052-eed7730a-d81d-11e7-85d0-c740f732c2a4.png)

- [ ] 'DELETE' button should delete the event

**Comment by gelaiong** [comment]
-Added Edit and Delete button
-Edit Button redirects to Edit Event Page
-Cannot delete yet
![edit delete button](https://user-images.githubusercontent.com/29205680/33543134-d4736732-d910-11e7-8124-c2d131554645.JPG)

**Comment by jenadrianne** [comment]
delete function (17145c6), edit function (60a95d3 , 692c0d7)
