### ISSUE TITLE
Issue at Admin Module - $upgradedBy undefined

### ISSUE THREAD

**Issue by famasboy88** [ejmstark/event_system#68]
Was this already resolved? 
![image](https://user-images.githubusercontent.com/23441168/33522756-122fd598-d82f-11e7-88d1-664bb4614d2a.png)

**Comment by jenadrianne** [comment]
nag gamit ka ug new na db ?

**Comment by famasboy88** [comment]
Master @ejmstark  dli updated ang DB diay sa Dev branch* ?  adtu ko ni download man
