### ISSUE TITLE
A lot of bugs after importing and using new DB (event_db_12_5_17.sql). @AllModules Please double check your queries in your models to fix these bugs.

### ISSUE THREAD

**Issue by famasboy88** [ejmstark/event_system#81]
![image](https://user-images.githubusercontent.com/23441168/33606674-3e270538-d9f9-11e7-84db-f1e42c2ceda5.png)

**Comment by ejmstark** [comment]
lage. wait lng guba ang messenger di ko ka chat ni lindo

**Comment by Jeylin123** [comment]
REMOVED DATE_ACCOUNT CREATED REPLACED WITH addedAt

ALL CHANGES WERE NOTED IN THE LOGS IN THE SOFTEN FB POST I POSTED WITH THE SQL
