### ISSUE TITLE
FRONTEND : REMOVE SEARCH BAR ON HOMEPAGE 

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#93]
**SIZE : 2**

- [ ] remove search bar

![image](https://user-images.githubusercontent.com/23441105/33824913-db1755aa-de9a-11e7-9a08-ba33132e101b.png)

**Comment by jenadrianne** [comment]
commit id : 255ef6d
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34154771-ab8a6d42-e4f1-11e7-82b3-aebec8b9ba0a.png)

**Comment by chinn015** [comment]
assigned to : Joanne Malaluan
