### ISSUE TITLE
FRONTEND: Match Announcement page to the system's theme

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#94]
**SIZE : 5**

**Comment by jenadrianne** [comment]
commit id  : c956e41
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34154893-1e40539c-e4f2-11e7-9c20-7ed8e290e8f7.png)

**Comment by chinn015** [comment]
assigned to : Joanne Malaluan and Diane Malazarte
