### ISSUE TITLE
FRONTEND : Fix image display for List View of events on Home page

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#95]
**SIZE : 3**

TASK DESCRIPTION : 

- CLICK THE HORIZONTAL LAYOUT BUTTON 
![image](https://user-images.githubusercontent.com/23441105/33825068-64029c94-de9b-11e7-8437-acffd6b8f959.png)

- FIX THE PICTURE DISPLAYED IN THE LAYOUT
![image](https://user-images.githubusercontent.com/23441105/33825089-720a5bd8-de9b-11e7-930e-e1578f9589c2.png)

**Comment by chinn015** [comment]
assigned to : Joanne Malaluan and Diane Malazarte

**Comment by jenadrianne** [comment]
commit id : 144c9d8
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34185828-a12a878a-e562-11e7-8b5c-7fc49772231f.png)
