### ISSUE TITLE
FRONTEND : Make Reports the landing page for Admin

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#96]
**SIZE : 2** 

TASK DESCRIPTION: 
- AFTER LOGGING IN AS ADMIN, THIS PAGE SHOULD BE LOADED FIRST INSTEAD OF EVENTS MANAGEMENT 

![image](https://user-images.githubusercontent.com/23441105/33825177-bf0583e0-de9b-11e7-975a-bef93ed27c2d.png)

**Comment by jenadrianne** [comment]
commit : c8fcffb
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34155421-31252a4e-e4f4-11e7-8995-43931f538a25.png)

**Comment by chinn015** [comment]
assigned to : Diane Malazarte
