### ISSUE TITLE
FRONTEND : Change font style on landing page navbar 

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#97]
**SIZE : 2**

- if the font is not installed in the pc the font is not loaded. find a way to fix it without forcing the user to install the font 

![image](https://user-images.githubusercontent.com/23441105/33825281-1f98e4b8-de9c-11e7-80f4-873991dda9b3.png)

**Comment by jenadrianne** [comment]
commit id :  c2763be
fixed : ( uninstalled the font while checking ) 
![image](https://user-images.githubusercontent.com/23441105/34154949-6181faa2-e4f2-11e7-8332-6dd2e3622f3b.png)

**Comment by chinn015** [comment]
assigned to :  Diane Malazarte
