### ISSUE TITLE
FRONTEND : Create Card Page on Admin 

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#98]
SIZE : 5

**Comment by jenadrianne** [comment]
commit : 373fc3a
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34155483-6f84e16c-e4f4-11e7-8605-8588ffc3c5ea.png)

**Comment by chinn015** [comment]
assigned to : Jennifer Caballes, Redenfloyd Cayanan and Joanne Malaluan
