### ISSUE TITLE
FRONTEND: Change "Edit Profile" link to button and transfer to better location on the page

### ISSUE THREAD

**Issue by jenadrianne** [ejmstark/event_system#99]
**SIZE : 2**

**Comment by jenadrianne** [comment]
commit : 8338773
fixed : 
![image](https://user-images.githubusercontent.com/23441105/34155003-a67965b4-e4f2-11e7-8c7a-d435ee9201ac.png)

**Comment by chinn015** [comment]
assigned to :  Joanne Malaluan
